apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - hpa-agent-api.yaml
  - hpa-burger-api.yaml
  - hpa-burger-mcp.yaml
  - pod-disruption-budgets.yaml
  - postgres-init-job.yaml
  - postgres-statefulset.yaml
