apiVersion: v1
kind: Service
metadata:
  name: burger-webapp
  labels:
    app: mcp-agent
    service: burger-webapp
    
spec:
  selector:
    app: mcp-agent
    service: burger-webapp
    
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer
