apiVersion: v1
kind: Service
metadata:
  name: burger-api
  labels:
    app: mcp-agent
    service: burger-api
    
spec:
  selector:
    app: mcp-agent
    service: burger-api
    
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
