apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Override PUBLIC_BASE_URL for dev environment
  PUBLIC_BASE_URL: "https://burger-api-dev.platform-engineering-demo.dev"
  DD_ENV: "dev"
  # PostgreSQL host for dev environment
  POSTGRES_HOST: "postgres-0.postgres.mcp-agent-dev.svc.cluster.local"
