apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - agent-api.yaml
  - agent-webapp.yaml
  - burger-api.yaml
  - burger-webapp.yaml
  - burger-mcp.yaml
  - postgres-statefulset.yaml
  - postgres-init-job.yaml
  - hpa-agent-api.yaml
  - hpa-burger-api.yaml
  - hpa-burger-mcp.yaml
  - pod-disruption-budgets.yaml

labels:
  - pairs:
      app: mcp-agent
